FROM fuzzer-system:parmesan



# build binutils 
WORKDIR  /work
RUN mkdir -p /targets/parmesan-unibench/bcfirst && mkdir -p /targets/parmesan-unibench/full  &&  apt-get update && apt-get install -y zip flex bison
COPY build_unibench.sh build_unibench.sh
RUN FORCE_UNSAFE_CONFIGURE=1 ./build_unibench.sh

WORKDIR  /work/parmesan
RUN ./misc/build_unibench.sh

COPY  --from=fuzzer-afl /targets/unibench /targets/parmesan-unibench/afl


