FROM fuzzer-system:libfuzzer
RUN apt-get update && apt-get install -y --no-install-recommends libstdc++-8-dev binutils build-essential make
ENV FORCE_UNSAFE_CONFIGURE=1
# build llvm with sync support (and proper timeout in fork mode)
#WORKDIR /build_clang/
#RUN git clone --depth=1 --single-branch --branch fuzzer_sync https://github.com/phi-go/llvm-project.git &&\
#    cd llvm-project && mkdir build && cd build &&\
#    cmake -G Ninja -DLLVM_TARGETS_TO_BUILD=Native -DCMAKE_BUILD_TYPE=Release \
#          -DLLVM_ENABLE_PROJECTS='clang;compiler-rt' -DCMAKE_INSTALL_PREFIX=/build_clang/install/ ../llvm &&\
#    ninja && ninja install

# build LAVA-M
WORKDIR  /work
RUN mkdir -p /targets/libfuzzer-lava && tar xfv lava_corpus.tar.xz

# build LAVA-M with libfuzzer support
COPY lavam/base64.c lava_corpus/LAVA-M/base64/coreutils-8.24-lava-safe/src/
COPY lavam/base64_fuzz.c lava_corpus/LAVA-M/base64/coreutils-8.24-lava-safe/
RUN cd lava_corpus/LAVA-M/base64/coreutils-8.24-lava-safe/ && make distclean && CC=clang CFLAGS="-O2 -fPIC -fno-omit-frame-pointer -gline-tables-only -fsanitize=fuzzer-no-link -fsanitize-coverage=trace-cmp,trace-gep,trace-div" ./configure --disable-silent-rules && make -j && clang -shared -O0 -fPIC -fno-omit-frame-pointer -gline-tables-only -fsanitize=fuzzer-no-link -fsanitize-coverage=trace-cmp,trace-gep,trace-div -Wl,--as-needed -o src/base64.so src/base64.o src/libver.a lib/libcoreutils.a  lib/libcoreutils.a && clang -fsanitize=fuzzer -Isrc/ -L. -g base64_fuzz.c -o /targets/libfuzzer-lava/base64 src/base64.so

COPY lavam/md5sum.c lava_corpus/LAVA-M/md5sum/coreutils-8.24-lava-safe/src/
COPY lavam/md5sum_fuzz.c lava_corpus/LAVA-M/md5sum/coreutils-8.24-lava-safe/
RUN cd lava_corpus/LAVA-M/md5sum/coreutils-8.24-lava-safe/ && make distclean && CC=clang CFLAGS="-O2 -fPIC -fno-omit-frame-pointer -gline-tables-only -fsanitize=fuzzer-no-link -fsanitize-coverage=trace-cmp,trace-gep,trace-div" ./configure --disable-silent-rules && make -j && clang -shared -O0 -fPIC -fno-omit-frame-pointer -gline-tables-only -fsanitize=fuzzer-no-link -fsanitize-coverage=trace-cmp,trace-gep,trace-div -Wl,--as-needed -o src/md5sum.so src/src_md5sum-md5sum.o src/libver.a lib/libcoreutils.a lib/libcoreutils.a && clang -fsanitize=fuzzer -Isrc/ -L. -g md5sum_fuzz.c -o /targets/libfuzzer-lava/md5sum src/md5sum.so

COPY lavam/uniq.c lava_corpus/LAVA-M/uniq/coreutils-8.24-lava-safe/src/
COPY lavam/uniq_fuzz.c lava_corpus/LAVA-M/uniq/coreutils-8.24-lava-safe/
RUN cd lava_corpus/LAVA-M/uniq/coreutils-8.24-lava-safe/ && CC=clang CFLAGS="-O2 -fPIC -fno-omit-frame-pointer -gline-tables-only -fsanitize=fuzzer-no-link -fsanitize-coverage=trace-cmp,trace-gep,trace-div" ./configure --disable-silent-rules && make -j && clang -shared -O0 -fPIC -fno-omit-frame-pointer -gline-tables-only -fsanitize=fuzzer-no-link -fsanitize-coverage=trace-cmp,trace-gep,trace-div -Wl,--as-needed -o src/uniq.so src/uniq.o src/libver.a lib/libcoreutils.a lib/libcoreutils.a && clang -fsanitize=fuzzer -Isrc/ -L. -g uniq_fuzz.c -o /targets/libfuzzer-lava/uniq src/uniq.so

COPY lavam/who.c lava_corpus/LAVA-M/who/coreutils-8.24-lava-safe/src/
COPY lavam/who_fuzz.c lava_corpus/LAVA-M/who/coreutils-8.24-lava-safe/
RUN cd lava_corpus/LAVA-M/who/coreutils-8.24-lava-safe/ && CC=clang CFLAGS="-O2 -fPIC -fno-omit-frame-pointer -gline-tables-only -fsanitize=fuzzer-no-link -fsanitize-coverage=trace-cmp,trace-gep,trace-div" ./configure --disable-silent-rules && make -j && clang -shared -O0 -fPIC -fno-omit-frame-pointer -gline-tables-only -fsanitize=fuzzer-no-link -fsanitize-coverage=trace-cmp,trace-gep,trace-div -Wl,--as-needed  -o src/who.so src/who.o src/libver.a lib/libcoreutils.a  lib/libcoreutils.a && clang -fsanitize=fuzzer -Isrc/ -L. -g who_fuzz.c -o /targets/libfuzzer-lava/who src/who.so

COPY afl_wrapper.py . 
