# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

FROM fuzzer-system:libfuzzer
#TODO change
RUN apt-get update && apt-get install -y make texinfo nano flex bison zip mmv help2man
COPY binutils /work/fuzzer-test-suite/binutils
WORKDIR /work/fuzzer-test-suite/binutils
#RUN git clone --recursive --depth 1 git://sourceware.org/git/binutils-gdb.git binutils-gdb

RUN git clone --recursive --depth 1 https://github.com/zhaoxiaoyunok/binutils-gdb.git && git clone --depth=1 https://github.com/DavidKorczynski/binutils-preconditions binutils-preconditions
ENV SRC=/work/fuzzer-test-suite/binutils OUT=/targets/binutils LIBFUZZER_SRC=/work/src/libfuzzer/ FUZZING_ENGINE=fsanitize_fuzzer SANITIZER=address

#ENV CFLAGS="-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link  -fsanitize-coverage=edge,trace-cmp,trace-gep,trace-div,indirect-calls -g"
#ENV CXXFLAGS="$CFLAGS -stdlib=libc++"

RUN mkdir /targets/binutils && ./build.sh && cd /targets/binutils && mkdir bin && cp fuzz* ./bin/ && cd bin && mmv fuzz_\* \#1

