FROM fuzzer-system:libfuzzer
WORKDIR /work
    
#these env variables refers to fuzzbench libfuzzer fuzzer.py
ENV CC=clang CXX=clang++ CFLAGS='-O1 -fno-omit-frame-pointer -fsanitize=fuzzer-no-link -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION' CXXFLAGS='-stdlib=libc++ -std=c++11  -O1 -fno-omit-frame-pointer -fsanitize=fuzzer-no-link -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION' CC=clang CXX=clang++ FUZZER_LIB='/usr/lib/libFuzzer.a'

WORKDIR /work/putone
#RUN cd freetype2-2017 && ./build.sh && cd ../harfbuzz-1.3.2 && ./build.sh && cd ../lcms-2017-03-21 && ./build.sh && cd ../libjpeg-turbo-07-2017 && ./build.sh && cd ../libxml2-v2.9.2 && cd ../proj4-2017-08-14 && ./build.sh && cd ../re2-2014-12-09 &&  ./build.sh && cd ../vorbis-2017-12-11 && ./build.sh && cd ../woff2-2016-05-06 && ./build.sh
 
