image: fedora:31

pipelines:
    default:
        - step:
            caches:
                - dnf
                - cargo
            script:
                - dnf install --refresh --assumeyes
                    clang llvm-devel llvm-test cmake make python3-lit git
                    openssh lld
                - sed --in-place=.orig
                      's/if (ARG_SHARED)/if (ARG_SHARED OR ARG_MODULE)/'
                      /usr/lib64/cmake/llvm/AddLLVM.cmake
                - curl --proto '=https' --tlsv1.2 -sSf --output /tmp/rustup-init
                      https://sh.rustup.rs
                - chmod +x /tmp/rustup-init
                - /tmp/rustup-init -y
                - source $HOME/.cargo/env
                - rustup install nightly
                - git clone git@bitbucket.org:vusec/id-assigner-pass.git
                            /tmp/id-assigner-pass
                - mkdir /tmp/id-assigner-build
                - cd /tmp/id-assigner-build
                - cmake -DCMAKE_BUILD_TYPE=Debug
                        -DCMAKE_INSTALL_PREFIX=/tmp/install_prefix
                        /tmp/id-assigner-pass
                - make install
                - mkdir /tmp/build
                - cd /tmp/build
                - rustup override set nightly
                        --path $BITBUCKET_CLONE_DIR
                - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
                        -DCMAKE_INSTALL_PREFIX=/tmp/install_prefix
                        $BITBUCKET_CLONE_DIR
                - make check

definitions:
    caches:
        dnf: /var/cache/dnf
        cargo: $HOME/.cargo
