networks:
  network_statsd_zxy:
    external:
      name: statsdserver_network_statsd_zxy
services:
  aflplusplus-0-exid1:
    depends_on:
    - framework-exid1
    - driver-aflplusplus-0-exid1
    environment:
      AFL_NO_AFFINITY: '1'
      AFL_STATSD_FUZZER_BANNER: aflplusplus-0-exid1
      OUTPUT_DIR: /data/aflplusplus-0-exid1
    image: fuzzer-aflplusplus-readelf
    networks:
      network_statsd_zxy:
        ipv4_address: 172.24.1.12
    volumes:
    - data-vol:/data
    - ./seeds/binutils/readelf:/in
  driver-aflplusplus-0-exid1:
    depends_on:
    - framework-exid1
    environment:
      ARG: /targets/binutils/bin/readelf -a @@
      FUZZER_NAME: aflplusplus-0-exid1
      FUZZER_TYPE: aflplusplus
      OUTPUT_DIR: /data/aflplusplus-0-exid1/
      URI_CONTROL: tcp://framework-exid1:3001
      URI_LISTENER: tcp://framework-exid1:3000
      URI_SCHEDULER: tcp://framework-exid1:3002
    image: fuzzer-generic-driver
    links:
    - framework-exid1
    networks:
      network_statsd_zxy:
        ipv4_address: 172.24.1.13
    pid: host
    volumes:
    - data-vol:/data
    - /var/run/docker.sock:/var/run/docker.sock
  driver-fairfuzz-0-exid1:
    depends_on:
    - framework-exid1
    environment:
      ARG: /targets/binutils/bin/readelf -a @@
      FUZZER_NAME: fairfuzz-0-exid1
      FUZZER_TYPE: fairfuzz
      OUTPUT_DIR: /data/fairfuzz-0-exid1/
      URI_CONTROL: tcp://framework-exid1:3001
      URI_LISTENER: tcp://framework-exid1:3000
      URI_SCHEDULER: tcp://framework-exid1:3002
    image: fuzzer-generic-driver
    links:
    - framework-exid1
    networks:
      network_statsd_zxy:
        ipv4_address: 172.24.1.15
    pid: host
    volumes:
    - data-vol:/data
    - /var/run/docker.sock:/var/run/docker.sock
  driver-mopt-0-exid1:
    depends_on:
    - framework-exid1
    environment:
      ARG: /targets/binutils/bin/readelf -a @@
      FUZZER_NAME: mopt-0-exid1
      FUZZER_TYPE: mopt
      OUTPUT_DIR: /data/mopt-0-exid1/
      URI_CONTROL: tcp://framework-exid1:3001
      URI_LISTENER: tcp://framework-exid1:3000
      URI_SCHEDULER: tcp://framework-exid1:3002
    image: fuzzer-generic-driver
    links:
    - framework-exid1
    networks:
      network_statsd_zxy:
        ipv4_address: 172.24.1.17
    pid: host
    volumes:
    - data-vol:/data
    - /var/run/docker.sock:/var/run/docker.sock
  driver-symcc-0-exid1:
    depends_on:
    - framework-exid1
    environment:
      ARG: /targets/binutils/bin/readelf -a @@
      FUZZER_NAME: symcc-0-exid1
      FUZZER_TYPE: symcc
      OUTPUT_DIR: /data/symcc-0-exid1/
      URI_CONTROL: tcp://framework-exid1:3001
      URI_LISTENER: tcp://framework-exid1:3000
      URI_SCHEDULER: tcp://framework-exid1:3002
    image: fuzzer-generic-driver
    links:
    - framework-exid1
    networks:
      network_statsd_zxy:
        ipv4_address: 172.24.1.19
    pid: host
    volumes:
    - data-vol:/data
    - /var/run/docker.sock:/var/run/docker.sock
  fairfuzz-0-exid1:
    depends_on:
    - framework-exid1
    - driver-fairfuzz-0-exid1
    environment:
      AFL_NO_AFFINITY: '1'
      AFL_STATSD_FUZZER_BANNER: fairfuzz-0-exid1
      OUTPUT_DIR: /data/fairfuzz-0-exid1
    image: fuzzer-fairfuzz-readelf
    networks:
      network_statsd_zxy:
        ipv4_address: 172.24.1.14
    volumes:
    - data-vol:/data
    - ./seeds/binutils/readelf:/in
  framework-exid1:
    environment:
      ANALYSIS_BIN_DIR: /work/analysis_binaries/readelf.analysis_binaries/
      ARG: -a @@
      INPUT_DIR: /in
      OUTPUT_DIR: /data/collab/out
      RUST_LOG: debug
      SCHEDULER: casefc
      URI_CONTROL: tcp://*:3001
      URI_LISTENER: tcp://*:3000
      URI_SCHEDULER: tcp://*:3002
    image: fuzzer-framework-all
    networks:
      network_statsd_zxy:
        ipv4_address: 172.24.1.5
    volumes:
    - data-vol:/data
    - ./seeds/binutils/readelf:/in
  mopt-0-exid1:
    depends_on:
    - framework-exid1
    - driver-mopt-0-exid1
    environment:
      AFL_NO_AFFINITY: '1'
      AFL_STATSD_FUZZER_BANNER: mopt-0-exid1
      OUTPUT_DIR: /data/mopt-0-exid1
    image: fuzzer-mopt-readelf
    networks:
      network_statsd_zxy:
        ipv4_address: 172.24.1.16
    volumes:
    - data-vol:/data
    - ./seeds/binutils/readelf:/in
  symcc-0-exid1:
    depends_on:
    - framework-exid1
    - driver-symcc-0-exid1
    environment:
      AFL_NO_AFFINITY: '1'
      AFL_STATSD_FUZZER_BANNER: symcc-0-exid1
      OUTPUT_DIR: /data/symcc-0-exid1
    image: fuzzer-symcc-readelf
    networks:
      network_statsd_zxy:
        ipv4_address: 172.24.1.18
    volumes:
    - data-vol:/data
    - ./seeds/binutils/readelf:/in
version: '2'
volumes:
  data-vol: {}
