FROM fuzzer-system:afl

ENV CC=afl-clang  CXX=afl-clang++

# build LAVA-M
WORKDIR  /work
RUN apt-get update && apt-get install -y texinfo && mkdir -p /targets/afl-lava/asan && tar xfv lava_corpus.tar.xz

#RUN wget http://panda.moyix.net/~moyix/lava_corpus.tar.xz && tar xfv lava_corpus.tar.xz
#RUN tar xfv lava_corpus.tar.xz

COPY build_lava.sh build_lava.sh
COPY coreutils-8.24-on-glibc-2.28.patch coreutils-8.24-on-glibc-2.28.patch
RUN FORCE_UNSAFE_CONFIGURE=1 ./build_lava.sh
