FROM fuzzer-system:afl

ENV CC=afl-clang  CXX=afl-clang++

# build binutils 
WORKDIR  /work
COPY build_unibench.sh build_unibench.sh
RUN mkdir -p /targets/afl-unibench && mkdir -p /targets/afl-unibench/asan && apt-get update && apt-get install -y zip flex bison && FORCE_UNSAFE_CONFIGURE=1 ./build_unibench.sh

