image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu20.04:latest

stages:
  - build
  - static-analysis
  - pages

autoconf:
  stage: build
  script:
    - sh build/gitlab-ci autoconf
  after_script:
    - 'cat autoconf-build/test/test-suite.log'

cmake-makefiles:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Unix Makefiles" Release

cmake-ninja:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Ninja" Debug

cmake-ninja-arm64:
  tags: [arm64,freebsd]
  stage: build
  script:
    - sh build/gitlab-ci cmake "Ninja" Release
  rules:
    - if: '$CI_PROJECT_PATH == "libtiff/libtiff"'

coverity:
  stage: static-analysis
  image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu20.04-coverity:latest
  script:
    - sh build/gitlab-ci coverity "Ninja" Debug
  only:
    refs:
      - master

pages:
  stage: pages
  script:
    - cp -r html public
  artifacts:
    name: $CI_PROJECT_NAME-$CI_JOB_NAME
    paths:
    - public
  only:
  - master
