FROM fuzzer-system:symcc



# build binutils 
WORKDIR  /work
RUN mkdir -p /targets/symcc-putone/afl && mkdir -p /targets/symcc-putone/symcc && apt-get update && apt-get install -y zip flex bison
COPY build_putone.sh build_putone.sh
RUN FORCE_UNSAFE_CONFIGURE=1 ./build_putone.sh

COPY  --from=fuzzer-afl /targets/putone/asan /targets/symcc-putone/afl

