FROM fuzzer-system:angora

# build binutils 
WORKDIR  /work
RUN mkdir -p /targets/angora-unibench/afl && mkdir -p /targets/angora-unibench/fast && mkdir -p /targets/angora-unibench/track && apt-get update && apt-get install -y zip flex bison

# build angora fast bins

COPY  --from=fuzzer-afl /targets/unibench /targets/angora-unibench/afl
COPY build_unibench.sh build_unibench.sh
RUN FORCE_UNSAFE_CONFIGURE=1 ./build_unibench.sh

