
# Jobs run per pull request submission
name: Run-checker CI
on: [pull_request, push]
jobs:
  run-checker:
    strategy:
      fail-fast: false
      matrix:
        opt: [
          no-cmp,
          no-cms,
          no-ct,
          no-dtls,
          no-ec,
          no-ec2m,
          no-legacy,
          no-sock,
          no-srp,
          no-srtp,
          enable-ssl-trace,
          no-tests,
          no-threads,
          no-tls,
          no-tls1_3,
          enable-trace enable-fips,
          no-ts,
          no-ui,
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: CC=clang ./config --banner=Configured --strict-warnings ${{ matrix.opt }} && perl configdata.pm --dump
    - name: make
      run: make -s -j4
    - name: make test
      run: make test HARNESS_JOBS=${HARNESS_JOBS:-4}
