name: Run-checker merge
# Jobs run per merge to master

on: [push]
jobs:
  run-checker:
    strategy:
      fail-fast: false
      matrix:
        opt: [
          enable-asan no-shared no-asm -DOPENSSL_SMALL_FOOTPRINT,
          no-dgram,
          no-dso,
          no-dynamic-engine,
          no-engine no-shared,
          no-err,
          no-filenames,
          enable-ubsan no-asm -DPEDANTIC -DOPENSSL_SMALL_FOOTPRINT -fno-sanitize=alignment,
          no-unit-test,
          enable-weak-ssl-ciphers,
          enable-zlib,
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: CC=clang ./config --banner=Configured --strict-warnings ${{ matrix.opt }} && perl configdata.pm --dump
    - name: make
      run: make -s -j4
    - name: make test
      run: make test HARNESS_JOBS=${HARNESS_JOBS:-4}
