FROM magma/fairfuzz/libpng
USER root
#rm /work for reduce the size of images
RUN export DEBIAN_FRONTEND=noninteractive   && apt-get update  && apt-get install -y tzdata && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  && dpkg-reconfigure --frontend noninteractive tzdata
RUN rm -rf /work && apt-get update && apt-get install -y build-essential python2.7-dev python3.7-dev python3-dev automake flex bison libglib2.0-dev libpixman-1-dev python3-setuptools  gcc-$(gcc --version|head -n1|sed 's/.* //'|sed 's/\..*//')-plugin-dev libstdc++-$(gcc --version|head -n1|sed 's/.* //'|sed 's/\..*//')-dev  libasound2-dev libflac-dev libogg-dev libtool libvorbis-dev libopus-dev libmp3lame-dev libmpg123-dev nasm zlib1g-dev liblzma-dev libjpeg-turbo8-dev libreadline-dev 

COPY magma /targets/magma
COPY magma/binutils /targets/binutils
COPY magma/unibench /targets/unibench
WORKDIR /work

ENV DEBIAN_FRONTEND=noninteractive

